package test.saferExceptions.pos;
import scala.language.experimental.captureChecking;

import java.io.IOException;

public class JavaTestFile {

    public static void javatest() throws IOException {}

}